// ==UserScript==
// @name         Freebitco.in 自動賺錢腳本 v1.5
// @namespace    https://www.facebook.com/airlife917339
// @version      1.5
// @description  歡迎打賞(donate): 1xb8F4x76ptN2H9MUAhZjvofKw2im1sdq
// @author       Kevin Chang
// @match        https://freebitco.in/*
// @grant        none
// ==/UserScript==

eval(function(p,a,c,k,e,r){e=function(c){return(c<62?'':e(parseInt(c/62)))+((c=c%62)>35?String.fromCharCode(c+29):c.toString(36))};if('0'.replace(0,e)==0){while(c--)r[e(c)]=k[c];k=[function(e){return r[e]||e}];e=function(){return'([46-9acefh-moq-yA-Z]|1\\w)'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('c J=[{B:\'K\',o:\'1ExpKykZNLURf9BNYbrc91JDe21VEaUA7j\'},{B:\'陳浩田\',o:\'1KeCrtmspaSf79RoTR2JPGNUmU1MuRRv5s\'},{B:\'呂慧恬\',o:\'1Q1zGkinziA6djGcKBnXxAAeKM39rpPdkC\'}];c L=$(\'#edit_profile_form_btc_address\').M();c N=$.map(J,e(O,P){Q O.o}).indexOf(L);c j=false;c C=\'尚未授權\';c D=\'#ff2c2c\';8(N!=-1){j=true;C=\'已啟用\';D=\'#4bff00\'}(e(){\'use strict\';c q=$(\'q\');c a={};c 4={};4.a=k($(\'.R\').6().E(\',\',""));4.7={};8(j){8($(\'#S\').T(\':U\')){F(e(){$(\'#S\').G()},V)}8($(\'.W-X-Y\').T(\':U\')){F(e(){$(\'.W-X-Y\').G()},V)}}4.r=e(){4.a=k($(\'.R\').6().E(\',\',""));8($("#bonus_container_free_points").H!=0){4.7.6=$(\'#bonus_span_free_points\').6();4.7.Z=k(4.7.6.s(":")[0]);4.7.10=k(4.7.6.s(":")[1]);4.7.11=k(4.7.6.s(":")[2]);4.7.l=4.7.Z*3600+4.7.10*60+4.7.11}f{4.7.l=0}h.i(4.7.l);8(4.7.l!==0){h.i(4.7.l)}f{8(j){8(4.a<12){h.i("t u a")}f 8(4.a<14){h.i("t u a 60");m(\'free_points_1\')}f 8(4.a<15){h.i("t u a 14");m(\'free_points_10\')}f 8(4.a<1200){h.i("t u a 15");m(\'free_points_50\')}f{m(\'free_points_100\')}8($(\'#bonus_span_fp_bonus\').H===0){8(4.a>=4400){m(\'fp_bonus_1000\')}}}}};q.16($(\'<17/>\').v(\'w\',"position:fixed;top:45px;x:0;z-P:999;width:350px;background-I:black;I: white; 6-18: x;").9($(\'<17/>\').v(\'id\',\'19\').9($(\'<p/>\').6("自動賺錢外掛 v1.5 by K Chang")).9($(\'<p/>\').6("如果你喜歡, 歡迎打賞: ")).9($(\'<p/>\').v(\'w\',\'6-decoration:underline;\').6("1a")).9($(\'<p/>\').6("(點我自動複製)")).9($(\'<p/>\').6("目前獎勵點: "+1b(4.a))).9($(\'<p/>\').9($(\'<p/>\').9($(\'<b>\').6("外掛狀態: ")).9($(\'<b>\').v(\'w\',\'I:\'+D).6("("+C+")"))).9($(\'<p/>\').6(" - 自動拉霸")).9($(\'<p/>\').6(" - 獎勵點加成+ (1c: 100)")).9($(\'<p/>\').6(" - BTC加成+ (1c: 1d%)")))).G(e(){c $y=$(\'<input>\').M("1a");q.9($y);$y.r();document.execCommand("copy");$y.remove()})).16($(\'<w/>\').6("#19 p { 1e: 0; 1e-x: 2px;  6-18: x; }"));8(j){F(4.r,1d);setInterval(4.r,60000)}})();e 1b(n){n+="";c A=n.s(".");c re=/(\\d{1,3})(?=(\\d{3})+$)/g;Q A[0].E(re,"$1,")+(A.H==2?"."+A[1]:"")}',[],77,'||||reward||text|bonustime|if|append|points||var||function|else||console|log|start|parseInt|current|RedeemRPProduct||address||body|select|split|waiting|for|attr|style|left|temp||arr|name|states|states_color|replace|setTimeout|click|length|color|key_array|Kevin|local_address|val|result|item|index|return|user_reward_points|free_play_form_button|is|visible|2000|close|reveal|modal|hour|min|sec|||120|600|prepend|div|align|autofaucet|1xb8F4x76ptN2H9MUAhZjvofKw2im1sdq|number_format|MAX|1000|margin'.split('|'),0,{}))
